### ISSUE TITLE
ICal url link error 

### ISSUE THREAD

**Issue by chadwixk** [DNNCommunity/DNN.Events#169]
## Describe the bug
DNN 9.2.2 / Events 7.0.2

When clicking on the iCal link for the calendar (https://mysite.com:443/DesktopModules/Events/EventVCal.aspx?ItemID=0&Mid=386&tabid=34 ), this error is generated:

```
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 3/5/2019 5:13:49 PM 
Event time (UTC): 3/6/2019 12:13:49 AM 
Event ID: 9789e5e0541e43d7aa3da371f6192c14 
Event sequence: 692 
Event occurrence: 5 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/9/ROOT-2-131962978226566285 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: C:\inetpub\wwwroot\mysite.com \ 
    Machine name: mysite.com  
 
Process information: 
    Process ID: 11928 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\mysite.com  
 
Exception information: 
    Exception type: ArgumentOutOfRangeException 
    Exception message: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DotNetNuke.Modules.Events.VEvent.CreateiCal(Int32 iTabID, Int32 iModuleID, Int64 iItemID, Int32 socialGroupId, String iCategoryName, Int32 iCategoryID, String iLocationName, Int32 iLocationID, String calname)
   at DotNetNuke.Modules.Events.VEvent.ProcessVCalRequest(HttpContext inContext)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

 
 
Request information: 
    Request URL: https://mysite.com:443/DesktopModules/Events/EventVCal.aspx?ItemID=0&Mid=386&tabid=34 
    Request path: /DesktopModules/Events/EventVCal.aspx 
    User host address: 
    User: 
    Is authenticated: True 
    Authentication Type: Forms 
    Thread account name: IIS APPPOOL\mysite.com 
 
Thread information: 
    Thread ID: 30 
    Thread account name: IIS APPPOOL\mysite.com  
    Is impersonating: False 
    Stack trace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at DotNetNuke.Modules.Events.VEvent.CreateiCal(Int32 iTabID, Int32 iModuleID, Int64 iItemID, Int32 socialGroupId, String iCategoryName, Int32 iCategoryID, String iLocationName, Int32 iLocationID, String calname)
   at DotNetNuke.Modules.Events.VEvent.ProcessVCalRequest(HttpContext inContext)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 
 
Custom event details: 
```

**Comment by EPTamminga** [comment]
Are you working in a test environment? 
If so, can you give the Events 7.0.3 pre-release a test with this?

**Comment by chadwixk** [comment]
Unfortunately, I don't have a test environment for this implementation.

**Comment by EPTamminga** [comment]
I cannot reproduce this on Events 0.7.00.03, so I assume it is solved in that version.
