### ISSUE TITLE
Events Module 07.00.06 throws Exception after upgrade to DNN 9.7.1

### ISSUE THREAD

**Issue by djamell** [DNNCommunity/DNN.Events#225]
## Describe the bug

After upgrading from DNN 9.6.2 to 9.7.1 the Events Module 07.00.06 throws the following Exception:

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

   at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.ReplaceTokens(String sourceText)
   at DotNetNuke.Modules.Events.TokenReplaceControllerClass.TokenLength(String sourceText, String customCaption, String customToken, Dictionary`2 dict)
   at DotNetNuke.Modules.Events.TokenReplaceControllerClass.TokenReplaceEvent(EventInfo eventInfo, String sourceText, EventSignupsInfo eventSignupsInfo, Boolean addsubmodulename, Boolean isEventEditor)
   at DotNetNuke.Modules.Events.EventRpt.BindDataGrid()
   at DotNetNuke.Modules.Events.EventRpt.Page_Load(Object sender, EventArgs e)

**Comment by valadas** [comment]
This issue was found on dnn 9.7.1 upgrade scenarios from versions before 9.7.0, There is a workaround documented in the (freshly updated) release notes here https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.7.1 and a fix has just been merged for the 9.7.2 release, it is currently released as a release candicate here for testing: https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.7.2-rc1
