### ISSUE TITLE
Error when upgrading Events 07.00.06 -> 07.00.07

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Events#233]
## Describe the bug
Scenario:
DNN 09.07.02
Events 07.00.06
Object Qualifier: dnn

## To Reproduce
1. Go to 'Extensions'
2. Click on 'Install Extension'
3. Install/Upgrade Events to version 07.00.07

    Failure SQL Execution resulted in following Exceptions:
    System.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "ModuleSettings.SettingName" could not be bound.
      at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
      at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
      at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
      at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
      at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
      at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
      at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
      at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
    ClientConnectionId:a76ed4ab-6635-4e81-9db5-516cfd7d03a8
    Error Number:4104,State:1,Class:16

## Expected behavior
Should install without error

## Additional context
The {databaseOwner}{objectQualifier syntax is missing in line 27 of the file 07.00.07.SqlDataProvider

## Hotfix
Unzip the installation package, edit the file /Installation/07.00.07.SqlDataprovider, replace line 27 by

        AND {databaseOwner}[{objectQualifier}ModuleSettings].SettingName = 'ModuleLocationIds';

Create a new installation package (by zipping the files again) and install it.

**Comment by MaiklT** [comment]
Or use the fixed install package...
[DNN_Events_07.00.07_Install-Fixed.zip](https://github.com/DNNCommunity/DNN.Events/files/6056531/DNN_Events_07.00.07_Install-Fixed.zip)

**Comment by EPTamminga** [comment]
@MaiklT Tnx for mentioning it here. I corrected the data script, updated the install pack zip 7.0.7 with the corrected script and replaced the install pack 7.0.7 here on GitHub with the corrected version. That should do the trick.
