### ISSUE TITLE
Error Opening Event Settings

### ISSUE THREAD

**Issue by tpperlman** [DNNCommunity/DNN.Events#37]
I installed (fresh, not an upgrade) DNN Events 6.3 into DNN v8.0.3 and receive the following error when I try to open the Edit Settings page:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

   at DotNetNuke.Modules.Events.EventSettings.LoadSettings()
   at DotNetNuke.Modules.Events.EventSettings.Page_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by tpperlman** [comment]
I actually realized that the error occurred because the page's parent was HOST, which might explain why that happens. I'll mark this as closed.
