### ISSUE TITLE
Specified cast is not valid - Error in 7.0

### ISSUE THREAD

**Issue by james7342** [DNNCommunity/DNN.Events#66]
Just upgraded my DNN 9.1.1 test site Events module to 7.0. Now receiving the below error message upon loading event's module on page.

From Log File
2018-05-08 08:44:01,544 [XXXXXX][Thread:12][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=88&error=Specified+cast+is+not+valid.&content=0
System.InvalidCastException: **Specified cast is not valid.**
   at DotNetNuke.Modules.Events.EventModuleSettings.UpdateDefaults()
   at DotNetNuke.Modules.Events.EventModuleSettings..ctor(Int32 moduleId, String localResourceFile)
   at DotNetNuke.Modules.Events.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile)
   at DotNetNuke.Modules.Events.EventBase.get_Settings()
   at DotNetNuke.Modules.Events.EventBase.GetThemeSettings()
   at DotNetNuke.Modules.Events.EventBase.SetTheme(Panel ctlPnlTheme)
   at DotNetNuke.Modules.Events.Events.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

From Admin Log:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:9ac6b087-17b6-41d5-9ce8-13c242eeb63f
AssemblyVersion:9.1.1
PortalId:0
UserId:1
TabId:88
RawUrl:/Calendar
Referrer:http://www.domain.com/About-Us
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
ExceptionHash:6Y9dOOT5b87rHkTELMputlEHIlQ=
Message:**Specified cast is not valid.**
StackTrace:
InnerMessage:**Specified cast is not valid.**
InnerStackTrace:
at DotNetNuke.Modules.Events.EventModuleSettings.UpdateDefaults() at DotNetNuke.Modules.Events.EventModuleSettings..ctor(Int32 moduleId, String localResourceFile) at DotNetNuke.Modules.Events.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile) at DotNetNuke.Modules.Events.EventBase.get_Settings() at DotNetNuke.Modules.Events.EventBase.GetThemeSettings() at DotNetNuke.Modules.Events.EventBase.SetTheme(Panel ctlPnlTheme) at DotNetNuke.Modules.Events.Events.Page_Load(Object sender, EventArgs e) at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by EPTamminga** [comment]
Thank you for documenting. 
I expect that we'll find some more issues with existing installs. We did some testing, but cannot verify every situation ourselves.

**Comment by james7342** [comment]
No worries. Let me know if you need to test and validate a fix since it's broken on my site.

**Comment by EPTamminga** [comment]
I think I have the debug version of the main DLL and the related PDB (attacheded as a zip here). If you put these 2 files in the bin folder of the test site and you can reproduce the error, I think you will get line #'s of the source code as well. That will make debugging easier.
[Events700_Debug_DLL.zip](https://github.com/DNNCommunity/DNN.Events/files/1984878/Events700_Debug_DLLs.zip)
Is probably has to do with the fact that VB allows more auto casting/type conversion than C#.

**Comment by EPTamminga** [comment]
Tnx, that helps

**Comment by james7342** [comment]
Same thing. I also attached the ModuleSettings stored in the DB for Events. Maybe it's due to a unique value?
[Query 1.pdf](https://github.com/DNNCommunity/DNN.Events/files/1998624/Query.1.pdf)


2018-05-13 10:29:59,399 [XXXXXX][Thread:35][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=56&error=Specified+cast+is+not+valid.&content=0
System.InvalidCastException: Specified cast is not valid.
   at DotNetNuke.Modules.Events.EventModuleSettings.UpdateDefaults() in C:\Tmp\DNNEvents\Components\EventModuleSettings.cs:line 1181
   at DotNetNuke.Modules.Events.EventModuleSettings..ctor(Int32 moduleId, String localResourceFile) in C:\Tmp\DNNEvents\Components\EventModuleSettings.cs:line 276
   at DotNetNuke.Modules.Events.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile) in C:\Tmp\DNNEvents\Components\EventModuleSettings.cs:line 757
   at DotNetNuke.Modules.Events.EventBase.get_Settings() in C:\Tmp\DNNEvents\Components\EventBase.cs:line 1313
   at DotNetNuke.Modules.Events.EventBase.GetThemeSettings() in C:\Tmp\DNNEvents\Components\EventBase.cs:line 472
   at DotNetNuke.Modules.Events.EventBase.SetTheme(Panel ctlPnlTheme) in C:\Tmp\DNNEvents\Components\EventBase.cs:line 425
   at DotNetNuke.Modules.Events.Events.Page_Load(Object sender, EventArgs e) in C:\Tmp\DNNEvents\Events.ascx.cs:line 69
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2018-05-13 10:30:58,484 [XXXXXX][Thread:30][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.InvalidCastException: Specified cast is not valid.
   at DotNetNuke.Modules.Events.EventModuleSettings.UpdateDefaults() in C:\Tmp\DNNEvents\Components\EventModuleSettings.cs:line 1181
   at DotNetNuke.Modules.Events.EventModuleSettings..ctor(Int32 moduleId, String localResourceFile) in C:\Tmp\DNNEvents\Components\EventModuleSettings.cs:line 276
   at DotNetNuke.Modules.Events.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile) in C:\Tmp\DNNEvents\Components\EventModuleSettings.cs:line 757
   at DotNetNuke.Modules.Events.EventNotification.CleanupExpired() in C:\Tmp\DNNEvents\Components\EventNotification.cs:line 187
   at DotNetNuke.Modules.Events.EventNotification.DoWork() in C:\Tmp\DNNEvents\Components\EventNotification.cs:line 55

**Comment by EPTamminga** [comment]
New attempt. Turned out that I was looking into the wrong .cs file. My Colleague Mark had a go at the cast error.

[Events700_Debug_DLLs-3.zip](https://github.com/DNNCommunity/DNN.Events/files/2000417/Events700_Debug_DLLs-3.zip)

**Comment by james7342** [comment]
That got it. The module loads now.

**Comment by gncube** [comment]
Thanks for sharing the DLLs it fixed first part of the problem. There is one more problem when trying to edit, or add **locations** I get an error. On the EventLog this is the log.

RawUrl:/training/calendar/ctl/Locations/mid/435

Referrer:https://wmrtc.org.uk/training/calendar

UserAgent:Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0

ExceptionHash:wAgu9RgLvLn8Hdzu68DGjIh2/D8=

Message:Value cannot be null. Parameter name: source

StackTrace:

InnerMessage:Value cannot be null. Parameter name: source

InnerStackTrace:

at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate) at DotNetNuke.Common.Lists.ListController.GetListEntryInfoItems(String listName, String parentKey) at DotNetNuke.Modules.Events.EventEditLocations.BindRegion() in C:\Tmp\DNNEvents\EventEditLocations.ascx.cs:line 147 at DotNetNuke.Modules.Events.EventEditLocations.Page_Load(Object sender, EventArgs e) in C:\Tmp\DNNEvents\EventEditLocations.ascx.cs:line 99 at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

I am running on a DNN9.1.0 
PRODUCT:
DNN Platform
VERSION:
9.1.0
HTML EDITOR PROVIDER:
DNNConnect.CKE
DATA PROVIDER:
SqlDataProvider
CACHING PROVIDER:
FileBasedCachingProvider
LOGGING PROVIDER:
DBLoggingProvider
FRIENDY URL PROVIDER:
DNNFriendlyUrl
FRIENDLY URLS ENABLED:
True
FRIENDLY URL TYPE:
Advanced
SCHEDULER MODE:
TIMER_METHOD
WEB FARM ENABLED:
False
CAS PERMISSIONS:
ReflectionPermission, WebPermission, AspNetHostingPermission
