### ISSUE TITLE
Installed on Evoq 9.1.1 and broke server

### ISSUE THREAD

**Issue by krankymonkee** [DNNCommunity/DNN.Events#79]
After upgrading to 7.0.0 from 6.3, the server is stuck trying to find /Install/UpgradeWizard.aspx

This upgrade was done after finding that 6.3 is not compatible with DNN 9..2 which we are upgrading to soon. After upgrading though, it looks like I have to roll back the entire server.

**Comment by krankymonkee** [comment]
It looks like the server was actually 9.1.1 - Seems we rolled back the server previously.  I am trying an update to 9.2 to see what happens.

**Comment by krankymonkee** [comment]
After updating I am getting the case error:

EventID: 51931147
TypeKey: PAGE_LOAD_EXCEPTION
CreateDate: 5/23/2018 3:37:08 PM
TypeCSSClass: Exception
Properties:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:f4650006-331d-4ee5-bae2-1b6530ec7684
Message: Specified cast is not valid.
InnerMessage: Specified cast is not valid.
InnerStackTrace: at DotNetNuke.Modules.Events.EventModuleSettings.UpdateDefaults()
at DotNetNuke.Modules.Events.EventModuleSettings..ctor(Int32 moduleId, String localResourceFile)
at DotNetNuke.Modules.Events.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile)
at DotNetNuke.Modules.Events.EventBase.get_Settings()
at DotNetNuke.Modules.Events.EventBase.GetThemeSettings()
at DotNetNuke.Modules.Events.EventBase.SetTheme(Panel ctlPnlTheme)
at DotNetNuke.Modules.Events.Events.Page_Load(Object sender, EventArgs e)
at System.Web.UI.Control.OnLoad(EventArgs e)
at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
TabId: 25162
RawUrl: /publichealth/WIC/Calendar
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by krankymonkee** [comment]
Interesting - I tested updating out other test server - EVOQ 9.2 Content from 6.2.1 to 7.0.0 and did not get the broken server, wanting /install/upgradewizard

But I do still get the cast error.

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:e1b2582a-1162-4756-bc0b-3e47af652ae6
AssemblyVersion:9.2.0
ExceptionHash:Ledph4f9B4Aope3O/ZtA3PbbsIo=
Message:Specified cast is not valid.
StackTrace:
InnerMessage:Specified cast is not valid.
InnerStackTrace:
at DotNetNuke.Modules.Events.EventModuleSettings.UpdateDefaults() at DotNetNuke.Modules.Events.EventModuleSettings..ctor(Int32 moduleId, String localResourceFile) at DotNetNuke.Modules.Events.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile) at DotNetNuke.Modules.Events.EventBase.get_Settings() at DotNetNuke.Modules.Events.EventBase.GetThemeSettings() at DotNetNuke.Modules.Events.EventBase.SetTheme(Panel ctlPnlTheme) at DotNetNuke.Modules.Events.Events.Page_Load(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by EPTamminga** [comment]
@krankymonkee 
We have covered most of the cast errors. If you can try the attached DLL's (just replace the ones in the bin\ folder of your site), I hope that you will find that these cast errors are gone.

[Events700_Debug_DLLs-3.zip](https://github.com/DNNCommunity/DNN.Events/files/2034434/Events700_Debug_DLLs-3.zip)

These DLL's will produce source code line numbers on errors, it will be easier to pinpoint the culprit.

BTW: I do not have an Evoq test site, so it might be that there Evoq specific errors.  Please create issues here, so we can solve them.

BTW2: interesting GitHub username you have :-)

**Comment by krankymonkee** [comment]
@EPTamminga 
Thanks :)

It looks like those DLLs solved the issues on this portal.  I will run tests through the other portals using the module to see if anything else comes up.

Regarding the initial issue, where after installing on 9.1.1 the server was stuck trying to redirect to /install/upgrade wizard - Do you have any idea what may have caused that?  Or, if it reoccurs in our PROD environment, how to address it?

Thanks for the help, and your hard work on the module!

**Comment by EPTamminga** [comment]
No further responses. Closing the issue.
