### ISSUE TITLE
Multiple Admin log errors - when page is refreshed or 

### ISSUE THREAD

**Issue by worldheadquarters** [DNNCommunity/DNN.Events#80]
The default view is the one below, after having clicked on one of the calendar icons, (not sure which one) now there is no response to clicking on the two calendar icons, , Refreshing the page creates four entries in the admin log:/  I am pasting them below in reverse order of appearance in the admin log.
Other information that might be useful.  I entered only one event and made it a recurring event. The system created a row for that event in the events table for each day of occurrence (36 rows total) and another record in the recurring events (EventsRecurMaster)  table.

![eventrs-screen shop](https://user-images.githubusercontent.com/12089478/40463399-25e687e0-5ee3-11e8-97de-de32a0dba9c6.png)

DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:84f6fec5-36f7-4fb6-8cec-c218e2fa37b2

AssemblyVersion:9.2.0

PortalId:0

UserId:1

TabId:33

RawUrl:/Events

Referrer:http://localhost/Events

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

ExceptionHash:7ghU+07YQj9wTdzRVsoBfWtV3p8=

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Events.EventList.gvEvents_RowCreated(Object sender, GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.OnRowCreated(GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource) at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding) at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls() at System.Web.UI.Control.EnsureChildControls() at System.Web.UI.Control.FindControl(String id, Int32 pathOffset) at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: Grinch
----------------------------------------------
ModuleId:625

ModuleDefId:124

FriendlyName:Events

ModuleControlSource:DesktopModules/Events/Events.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:1ff6e8df-d6f3-4971-8fbb-77375f899c62

AssemblyVersion:9.2.0

PortalId:0

UserId:1

TabId:33

RawUrl:/Events

Referrer:http://localhost/Events

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

ExceptionHash:yuG3T02U6tJdS56UVFj2mfIrHWs=

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Events.EventList.gvEvents_RowCreated(Object sender, GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.OnRowCreated(GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource) at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding) at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls() at System.Web.UI.Control.EnsureChildControls() at System.Web.UI.WebControls.CompositeDataBoundControl.get_Controls() at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState) at System.Web.UI.Control.LoadViewStateRecursive(Object savedState) at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState) at System.Web.UI.Control.LoadViewStateRecursive(Object savedState) at System.Web.UI.Control.AddedControl(Control control, Int32 index) at DotNetNuke.Modules.Events.Events.LoadModuleControl()
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: Grinch
-------------------------------------------------------

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:9163cbbf-c9e8-4f62-85d0-1e5bb686384b

AssemblyVersion:9.2.0

PortalId:0

UserId:1

TabId:33

RawUrl:/Events

Referrer:http://localhost/Events

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

ExceptionHash:ZipaojJC76rLcsNtoEjF4N6xsRs=

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Events.EventList.gvEvents_RowCreated(Object sender, GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.OnRowCreated(GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource) at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding) at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls() at System.Web.UI.Control.EnsureChildControls() at System.Web.UI.Control.FindControl(String id, Int32 pathOffset) at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: Grinch
---------------------------------------------------
ModuleId:625

ModuleDefId:124

FriendlyName:Events

ModuleControlSource:DesktopModules/Events/Events.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:84681ade-b31f-4583-b728-6a9048fd659c

AssemblyVersion:9.2.0

PortalId:0

UserId:1

TabId:33

RawUrl:/Events

Referrer:http://localhost/Events

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

ExceptionHash:hpwkeiUiPUuiUspqrEa2UzxxQTo=

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Events.EventList.gvEvents_RowCreated(Object sender, GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.OnRowCreated(GridViewRowEventArgs e) at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource) at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding) at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls() at System.Web.UI.Control.EnsureChildControls() at System.Web.UI.WebControls.CompositeDataBoundControl.get_Controls() at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState) at System.Web.UI.Control.LoadViewStateRecursive(Object savedState) at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState) at System.Web.UI.Control.LoadViewStateRecursive(Object savedState) at System.Web.UI.Control.AddedControl(Control control, Int32 index) at DotNetNuke.Modules.Events.Events.LoadModuleControl()
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: Grinch

**Comment by worldheadquarters** [comment]
Can duplicate the issue by clicking on week view, then clicking on month view.  Month view does not appear and clicking on week view again has no effect. (is this what list view is supposed to look like?)  There is no icon for week view.

**Comment by valadas** [comment]
May have been fixed with #100 and #97
