### ISSUE TITLE
When Clicking to go back to April - Critical Error

### ISSUE THREAD

**Issue by krankymonkee** [DNNCommunity/DNN.Events#81]
Looking at the month view of May, I clicked on the link in the top left for April:

EventID: 23415796
TypeKey: PAGE_LOAD_EXCEPTION
CreateDate: 5/24/2018 1:25:16 PM
PortalID: 74
TypeCSSClass: Exception
Properties:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:a78920fc-f696-483e-b140-b2f264dd6475
Message: Value cannot be null. Parameter name: input
InnerMessage: Value cannot be null. Parameter name: input
InnerStackTrace: at System.Text.RegularExpressions.Regex.Match(String input, Int32 startat)
at System.Web.UI.ScriptRegistrationManager.WriteScriptWithTags(HtmlTextWriter writer, String token, RegisteredScript activeRegistration)
at System.Web.UI.ScriptRegistrationManager.RenderActiveScriptBlocks(List`1 updatePanels, HtmlTextWriter writer, String token, List`1 scriptRegistrations)
at System.Web.UI.ScriptRegistrationManager.RenderActiveScripts(List`1 updatePanels, HtmlTextWriter writer)
at System.Web.UI.PageRequestManager.ProcessScriptRegistration(HtmlTextWriter writer)
at System.Web.UI.PageRequestManager.RenderPageCallback(HtmlTextWriter writer, Control pageControl)
at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer)
at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer)
at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
TabId: 16707
RawUrl: /publichealth/Immunization/REgionalWorkshops
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by EPTamminga** [comment]
Should be solved in DNN.Events 07.00.01
